from fastapi import APIRouter

router = APIRouter(prefix="/api/v1")

# FF autogenerated ping for feature #74, corr_id=39b5b47e-fa68-49c3-8485-1ae64fafe280
@router.get("/ping")
async def ping():
    return {"ping": "pong"}
