"""init

Revision ID: 0001
Revises: 
Create Date: 2025-08-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postings_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('posting_id', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'posting_id')
    )
    op.create_table('postings_flat',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('posting_id', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('discount_mp', sa.Numeric(), nullable=True),
    sa.Column('final_price', sa.Numeric(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.UniqueConstraint('source', 'posting_id', 'sku')
    )
    op.create_table('etl_watermarks',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_successful_iso', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('NEW','RUNNING','DONE','RETRYABLE_ERROR','FAILED')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('agent_role', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_registry',
    sa.Column('doc_name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('doc_name')
    )
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('agent_role', sa.Text(), nullable=False),
    sa.Column('artifact_manifest_json', sa.Text(), nullable=False),
    sa.Column('commit_id', sa.Text(), nullable=True),
    sa.Column('related_docs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_log')
    op.drop_table('doc_registry')
    op.drop_table('agent_events')
    op.drop_table('settings')
    op.drop_table('jobs')
    op.drop_table('etl_watermarks')
    op.drop_table('postings_flat')
    op.drop_table('postings_raw')
    # ### end Alembic commands ###