"""add_type_field_to_features

Revision ID: 2ece5b93e49c
Revises: 8cef162a3852
Create Date: 2025-08-27 22:15:49.661984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ece5b93e49c'
down_revision: Union[str, None] = '8cef162a3852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем batch mode для SQLite
    with op.batch_alter_table("features", schema=None) as batch_op:
        # Добавляем поле type с дефолтным значением и constraint
        batch_op.add_column(sa.Column('type', sa.Text(), nullable=False, 
                                     server_default='INTERNAL'))
        batch_op.create_check_constraint("ck_features_type", 
                                        "type IN ('INTERNAL', 'BUSINESS')")
    
    # Удаляем server_default после создания колонки
    with op.batch_alter_table("features", schema=None) as batch_op:
        batch_op.alter_column('type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем batch mode для SQLite
    with op.batch_alter_table("features", schema=None) as batch_op:
        # Удаляем check constraint и колонку
        batch_op.drop_constraint("ck_features_type", type_="check")
        batch_op.drop_column('type')
    # ### end Alembic commands ###
