"""code_registry_symbol_index_call_graph_edges

Revision ID: 6547841c0d52
Revises: 0001
Create Date: 2025-08-21 17:06:04.591642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6547841c0d52'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('symbol_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('symbol_name', sa.Text(), nullable=False),
    sa.Column('symbol_type', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_path'], ['code_registry.file_path'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_symbol', sa.Text(), nullable=False),
    sa.Column('target_symbol', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_path'], ['code_registry.file_path'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_graph_edges')
    op.drop_table('symbol_index')
    op.drop_table('code_registry')
    # ### end Alembic commands ###
