"""add_backlog_tables_features_tasks_graph_runs

Revision ID: 7f0adda46c0c
Revises: 6547841c0d52
Create Date: 2025-08-21 21:29:41.853792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0adda46c0c'
down_revision: Union[str, None] = '6547841c0d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('intent_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('env', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("status IN ('NEW','PLANNED','RUNNING','DONE','FAILED')"),
    )
    
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('dsl_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('budget_tokens', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.CheckConstraint("status IN ('NEW','RUNNING','DONE','RETRYABLE_ERROR','FAILED')"),
    )
    
    op.create_table('graph_runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('graph_name', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('last_checkpoint_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    )
    
    # Добавляем индексы для улучшения производительности
    op.create_index('idx_features_status', 'features', ['status'])
    op.create_index('idx_features_priority', 'features', ['priority'])
    op.create_index('idx_tasks_feature_id', 'tasks', ['feature_id'])
    op.create_index('idx_tasks_status', 'tasks', ['status'])
    op.create_index('idx_tasks_role', 'tasks', ['role'])
    op.create_index('idx_graph_runs_feature_id', 'graph_runs', ['feature_id'])
    op.create_index('idx_graph_runs_status', 'graph_runs', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индексы
    op.drop_index('idx_graph_runs_status', table_name='graph_runs')
    op.drop_index('idx_graph_runs_feature_id', table_name='graph_runs')
    op.drop_index('idx_tasks_role', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_feature_id', table_name='tasks')
    op.drop_index('idx_features_priority', table_name='features')
    op.drop_index('idx_features_status', table_name='features')
    
    # Удаляем таблицы
    op.drop_table('graph_runs')
    op.drop_table('tasks')
    op.drop_table('features')
    # ### end Alembic commands ###
