"""add env to graph_runs

Revision ID: 8cef162a3852
Revises: 85912b080390
Create Date: 2025-08-25 18:44:36.848763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cef162a3852'
down_revision: Union[str, None] = '85912b080390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    columns = [c['name'] for c in inspector.get_columns('graph_runs')]
    if 'env' not in columns:
        op.add_column('graph_runs', sa.Column('env', sa.String(length=32), nullable=True))
        op.execute("UPDATE graph_runs SET env='test' WHERE env IS NULL")

    indexes = [idx['name'] for idx in inspector.get_indexes('graph_runs')]
    if 'idx_graph_runs_feat_env_status' not in indexes:
        op.create_index('idx_graph_runs_feat_env_status', 'graph_runs', ['feature_id', 'env', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_graph_runs_feat_env_status', table_name='graph_runs')
    op.drop_column('graph_runs', 'env')
    # ### end Alembic commands ###
