"""add_env_to_graph_runs_and_unique_index

Revision ID: a1b2c3d4e5f0
Revises: 7f0adda46c0c
Create Date: 2025-08-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f0'
down_revision = '7f0adda46c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверим, существует ли уже поле env
    inspector = sa.inspect(op.get_bind())
    columns = [c['name'] for c in inspector.get_columns('graph_runs')]
    
    # Добавляем поле env в таблицу graph_runs, если его ещё нет
    if 'env' not in columns:
        op.add_column('graph_runs', sa.Column('env', sa.Text(), nullable=True))
        
        # Заполняем поле env значением 'test' для существующих записей
        connection = op.get_bind()
        connection.execute(
            sa.text("UPDATE graph_runs SET env = 'test' WHERE env IS NULL")
        )
    
    # Проверим, существует ли уже индекс
    indexes = [idx['name'] for idx in inspector.get_indexes('graph_runs')]
    
    # Добавляем уникальный индекс для активных run, если его ещё нет
    if 'idx_graph_runs_active_unique' not in indexes:
        # Активный run - это run со статусом NEW, RUNNING или PENDING
        # Для простоты создадим уникальный индекс на (feature_id, env) с фильтром по активным статусам
        # В SQLite мы можем создать частичный индекс
        op.create_index(
            'idx_graph_runs_active_unique', 
            'graph_runs', 
            ['feature_id', 'env'],
            unique=True,
            sqlite_where=sa.text("status IN ('NEW', 'RUNNING', 'PENDING')")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем уникальный индекс
    op.drop_index('idx_graph_runs_active_unique', table_name='graph_runs')
    
    # Удаляем поле env
    op.drop_column('graph_runs', 'env')
    # ### end Alembic commands ###