#!/usr/bin/env python3
"""
Узел TestSynth: генерирует приёмочные тесты на основе артефактов/спека
и сохраняет файл test_acceptance_oracles.py в каталоге артефактов ран-а.
Тесты:
- базовые оракулы (openapi/health) для приложения
- динамические проверки импортируемых роутеров из artifact_manifest.yaml
- spec‑driven API‑тесты по architect_spec.json (method/path/schema)
- миграционные проверки Alembic (upgrade/downgrade) при наличии требований в спецификации
"""

from __future__ import annotations

import os
from typing import Any, Dict
import structlog
from app.graph.types import RunCtx

logger = structlog.get_logger()

TEST_FILE_NAME = "test_acceptance_oracles.py"

TEST_TEMPLATE = r"""
# autogenerated acceptance oracles (Spec-driven)
from __future__ import annotations
import json
import os
import importlib
import subprocess
from typing import Any, Dict, List

try:
    from fastapi import FastAPI  # type: ignore
    from fastapi.testclient import TestClient  # type: ignore
except Exception:
    FastAPI = None  # type: ignore
    TestClient = None  # type: ignore



def _project_root() -> str:
    return "/opt/feature-factory"


def _artifacts_dir() -> str:
    return os.path.dirname(__file__)


def _read_manifest() -> dict:
    path = os.path.join(_artifacts_dir(), 'artifact_manifest.yaml')
    if not os.path.exists(path):
        return {}
    import yaml  # type: ignore
    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f) or {}


def _read_spec() -> dict:
    path = os.path.join(_artifacts_dir(), 'architect_spec.json')
    if not os.path.exists(path):
        return {}
    with open(path, 'r', encoding='utf-8') as f:
        try:
            return json.load(f) or {}
        except Exception:
            return {}


def _build_app_from_manifest() -> FastAPI:
    m = _read_manifest()
    files = (m or {}).get('files', [])
    app = FastAPI()
    for f in files:
        if not f.startswith('app/api/') or not f.endswith('.py'):
            continue
        module = 'app.' + f.replace('/', '.').replace('.py', '')
        try:
            mod = importlib.import_module(module)
            router = getattr(mod, 'router', None)
            if router is not None:
                app.include_router(router)
        except Exception:
            continue
    return app


def _get_client() -> TestClient:
    # Предпочитаем реальный app.main
    try:
        from app.main import app as real_app
        if TestClient is None:
            raise RuntimeError("no fastapi available")
        return TestClient(real_app)
    except Exception:
        pass
    if TestClient is None or FastAPI is None:
        # FastAPI не доступен — пропускаем проверки, которые его требуют
        raise SystemExit(0)
    # Fallback: собираем приложение из сгенерированных роутеров
    return TestClient(_build_app_from_manifest())


def test_health_and_openapi_available():
    client = _get_client()
    try:
        r1 = client.get('/openapi.json')
        assert r1.status_code == 200
    except Exception:
        pass
    try:
        r2 = client.get('/health/live')
        assert r2.status_code == 200
    except Exception:
        pass


def test_generated_routers_have_at_least_one_2xx_endpoint():
    m = _read_manifest()
    files = (m or {}).get('files', [])
    found_any = False
    for f in files:
        if not f.startswith('app/api/') or not f.endswith('.py'):
            continue
        module = 'app.' + f.replace('/', '.').replace('.py', '')
        try:
            mod = importlib.import_module(module)
            router = getattr(mod, 'router', None)
            if router is None:
                continue
            app = FastAPI()
            app.include_router(router)
            client = TestClient(app)
            # ищем роуты без path-параметров и дергаем GET
            for route in router.routes:
                try:
                    path = getattr(route, 'path_format', None) or getattr(route, 'path', None)
                    methods = set(getattr(route, 'methods', set()) or [])
                    if not path or '{' in path or 'GET' not in methods:
                        continue
                    resp = client.get(path)
                    assert 200 <= resp.status_code < 300
                    found_any = True
                    break
                except Exception:
                    continue
        except Exception:
            continue
    assert found_any, 'no testable GET endpoints discovered in generated routers'


def test_api_acceptance_from_spec():
    spec = _read_spec()
    acceptance = (spec or {}).get('acceptance_tests', {})
    api_tests: List[Dict[str, Any]] = acceptance.get('api', []) or []
    if not api_tests:
        return  # нет спеков — считаем успешно
    client = _get_client()
    try:
        import jsonschema  # type: ignore
    except Exception:
        jsonschema = None  # type: ignore
    for i, case in enumerate(api_tests):
        method = (case.get('method') or 'GET').upper()
        path = case.get('path') or '/'
        expected_status = int(case.get('expected_status') or 200)
        body = case.get('body')
        if method == 'GET':
            resp = client.get(path)
        elif method == 'POST':
            resp = client.post(path, json=body)
        elif method == 'PUT':
            resp = client.put(path, json=body)
        elif method == 'PATCH':
            resp = client.patch(path, json=body)
        elif method == 'DELETE':
            resp = client.delete(path)
        else:
            # неизвестный метод — пропускаем
            continue
        assert resp.status_code == expected_status, f"{method} {path}: {resp.status_code} != {expected_status}"
        schema = case.get('json_schema')
        if schema and jsonschema is not None:
            try:
                data = resp.json()
            except Exception:
                assert False, f"{method} {path}: response is not JSON"
            jsonschema.validate(instance=data, schema=schema)


def test_migrations_upgrade_downgrade_if_requested():
    spec = _read_spec()
    migrations = (spec or {}).get('migrations') or []
    if not migrations:
        return  # нет требований — тест не обязателен
    alembic_bin = os.path.join(_project_root(), '.venv', 'bin', 'alembic')
    if not os.path.exists(alembic_bin):
        # нет alembic — пропускаем
        return
    db_file = os.path.join(_artifacts_dir(), 'tmp_migrate.db')
    db_url = f"sqlite:////{db_file}"
    env = os.environ.copy()
    env['DATABASE_URL'] = db_url
    cwd = _project_root()
    # upgrade head
    r1 = subprocess.run([alembic_bin, '-c', 'alembic.ini', 'upgrade', 'head'], cwd=cwd, env=env, capture_output=True, text=True)
    assert r1.returncode == 0, f"alembic upgrade failed: {r1.stderr}"
    # downgrade base
    r2 = subprocess.run([alembic_bin, '-c', 'alembic.ini', 'downgrade', 'base'], cwd=cwd, env=env, capture_output=True, text=True)
    assert r2.returncode == 0, f"alembic downgrade failed: {r2.stderr}"
    try:
        os.remove(db_file)
    except Exception:
        pass
"""


def _ensure_artifacts_dir(state: Dict[str, Any]) -> str:
    run_ctx = state.get("run_ctx")
    run_id = run_ctx.run_id if run_ctx else "run"
    artifacts_dir = state.get("artifacts_dir") or f"/opt/feature-factory/tmp/{run_id}"
    os.makedirs(artifacts_dir, exist_ok=True)
    return artifacts_dir


async def test_synth_node(state: Dict[str, Any]) -> Dict[str, Any]:
    try:
        run_ctx: RunCtx | None = state.get("run_ctx")
        if not run_ctx:
            raise ValueError("Run context not found in state")
        artifacts_dir = _ensure_artifacts_dir(state)
        test_path = os.path.join(artifacts_dir, TEST_FILE_NAME)
        with open(test_path, 'w', encoding='utf-8') as f:
            f.write(TEST_TEMPLATE)
        logger.info(
            "test_synth_completed",
            component="graph",
            agent_role="TestSynth",
            run_id=run_ctx.run_id,
            feature_id=run_ctx.feature_id,
            test_file=test_path,
        )
        st = dict(state)
        st.update({"status": "test_synth_completed", "artifacts_dir": artifacts_dir})
        return st
    except Exception as e:
        logger.error("test_synth_failed", component="graph", agent_role="TestSynth", error=str(e))
        return {"status": "test_failed", "error": str(e)}
